// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.5
// source: sorting.proto

package sortingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sorter_SortPersons_FullMethodName = "/sorting.Sorter/SortPersons"
)

// SorterClient is the client API for Sorter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SorterClient interface {
	SortPersons(ctx context.Context, in *SortPersonsRequest, opts ...grpc.CallOption) (*SortPersonsResponse, error)
}

type sorterClient struct {
	cc grpc.ClientConnInterface
}

func NewSorterClient(cc grpc.ClientConnInterface) SorterClient {
	return &sorterClient{cc}
}

func (c *sorterClient) SortPersons(ctx context.Context, in *SortPersonsRequest, opts ...grpc.CallOption) (*SortPersonsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SortPersonsResponse)
	err := c.cc.Invoke(ctx, Sorter_SortPersons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SorterServer is the server API for Sorter service.
// All implementations must embed UnimplementedSorterServer
// for forward compatibility.
type SorterServer interface {
	SortPersons(context.Context, *SortPersonsRequest) (*SortPersonsResponse, error)
	mustEmbedUnimplementedSorterServer()
}

// UnimplementedSorterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSorterServer struct{}

func (UnimplementedSorterServer) SortPersons(context.Context, *SortPersonsRequest) (*SortPersonsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SortPersons not implemented")
}
func (UnimplementedSorterServer) mustEmbedUnimplementedSorterServer() {}
func (UnimplementedSorterServer) testEmbeddedByValue()                {}

// UnsafeSorterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SorterServer will
// result in compilation errors.
type UnsafeSorterServer interface {
	mustEmbedUnimplementedSorterServer()
}

func RegisterSorterServer(s grpc.ServiceRegistrar, srv SorterServer) {
	// If the following call pancis, it indicates UnimplementedSorterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sorter_ServiceDesc, srv)
}

func _Sorter_SortPersons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SortPersonsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SorterServer).SortPersons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sorter_SortPersons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SorterServer).SortPersons(ctx, req.(*SortPersonsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sorter_ServiceDesc is the grpc.ServiceDesc for Sorter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sorter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sorting.Sorter",
	HandlerType: (*SorterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SortPersons",
			Handler:    _Sorter_SortPersons_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sorting.proto",
}
